config/routes.rb
Quizapp::Application.routes.draw do
  get "exam/show"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users
   get "users/sign_up"
  get "users/sign_in"

  resources :questions

  get "quiz/index"

  post "quiz/start"

  get "quiz/question"

  post "quiz/question"

  post "quiz/answer"

  get "quiz/end"

  post "choices/create"

  post "choices/destroy"

root :to => "quiz#index"

   match ':controller(/:action(/:id))(.:format)'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
end

app/models/exam.rb
class Exam < ActiveRecord::Base
   attr_accessible :email,:score,:question_id,:user_id
  has_many :questions, :through=>:user_answers
  has_many :user_answers
  belongs_to :user
  set_primary_key 'score'
#set_primary_key :email
#set_primary_key :score
  has_one :question_id
end

app/models/question.rb
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Author::    1165536 Juliana Pena

class Question < ActiveRecord::Base
  has_many :choices
  has_many :exam, :through=>:user_answers
  has_one :user_answer
  
  def answer
	 uncorrect
	 choices.select {|c| c.correct}[0]
  end	
  
  def uncorrect
	 choices.each {|c| c.correct = false}
  end
  
  def answer= choice
	 if !answer.nil?
		answer.correct = false
	 end
	 
	 if choices.include? choice
		choice.correct = true
	 else
		choices << choice
		choice.correct = true
	 end
  end
def to_s
  text
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :school_name, :mobile_no
  # attr_accessible :title, :body
  has_one :test
end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :question
  belongs_to :exam
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
   #before_filter :authenticate_user!
end

app/controllers/choices_controller.rb
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Author::    1165536 Juliana Pena

class ChoicesController < ApplicationController
  
  def create
	 @question = Question.find(params[:question])
	 text = params[:text]
	 correct = params[:correct] == "1"
	 new = Choice.create(:text => text, :correct => correct, :question_id => @question.id)
	 
	 if new.correct
		@question.answer = new
	 end
	 
	 redirect_to question_path(@question)
  end
  
  def destroy
	 @question = Question.find(params[:question])
	 @choice = Choice.find(params[:choice])
	 @choice.destroy
	 redirect_to question_path(@question)
  end
  
end

app/controllers/exam_controller.rb
class ExamController < ApplicationController
  def show
    
@exam = Exam.find(:all)

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
  def index
    @questions = Question.all
    @questions.sort! {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
puts "............"
p @question
puts "..............."    
@question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end
  
  def start
	 total = 5
	 all = Question.find(:all).map {|x| x.id}
	 session[:questions] = all.sort_by{rand}[0..(total-1)]
	 
	 session[:total]   = total
	 session[:current] = 0
	 session[:correct] = 0
	 
	 redirect_to :action => "question"
  end
  def question
          
         
	 @current = session[:current]
	 @total   = session[:total]
	 if @current >= @total
		redirect_to :action => "end"
		return
	 end
	
	 @question = Question.find(session[:questions][@current])
	 @choices = @question.choices.sort_by{rand}
	 
	 
	 session[:question] = @question
	 session[:choices] = @choices
	 
	 
	
  end

  def answer
	 @current = session[:current]
	 @total   = session[:total]
	 
	 choiceid = params[:choice]
	 
	 @question = session[:question]
	 @choices  = session[:choices]
	 UserAnswer.create(:question_id=>session[:question].id,:choice_id=>choiceid)
	 @choice = choiceid ? Choice.find(choiceid) : nil
	 if @choice and @choice.correct
		@correct = true
		session[:correct] += 1
	 else
		@correct = false
	 end
	 
	 session[:current] += 1
   redirect_to :action=>"question"
  end

  def end
	 @correct = session[:correct]
	 @total   = session[:total]
	 @score = @correct * 100 / @total
  end
  
  
  def submitresult
    
    @addresult = Exam.new 
     @correct = session[:correct]
    @addresult.score=@correct
  
    @addresult.user_id = current_user.id
    @addresult.email = current_user.email
    @addresult.save
    
    
end

  

end

app/controllers/sessions_controller.rb
  class SessionsController < Devise::SessionsController
  respond_to :html
  def destroy
    super
    reset_session
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_out
    
    reset_session
    redirect_to :action=>'sign_in'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Author::    1165536 Juliana Pena

module ChoicesHelper
end

app/helpers/exam_helper.rb
module ExamHelper
end

app/helpers/questions_helper.rb
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Author::    1165536 Juliana Pena

module QuestionsHelper
end

app/helpers/quiz_helper.rb
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Author::    1165536 Juliana Pena

module QuizHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exam/show.html.erb
<h1>exam results</h1>

<table >

  <tr>
    <th>email</th>
    <th>score</th>
    
  </tr>


<% Exam.all.each do |exam| %>
<tr>  
<%= exam.id %>
  <td><%= exam.email %></td>
<td><%= exam.score %></td>
</tr>
<% end %>

</table>

app/views/layouts/application.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<p><%= notice %></p>
<p><%= alert %></p>

<div id="main">
  <% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<%end%>
  <%= yield %>
  
  <hr />
  <div id="footer">
	 <p>
			Created by <a href="http://www.brilliance-works.com">Brilliance-works</a>
	 </p>
  </div>
</div>



</body>
</html>

app/views/layouts/question.html.erb
<!DOCTYPE html>
<html>
<body>

   
    <html>
    <head>
    <title>Countdown</title>
    <div class = "timer",style="position: fixed; top: 62px; right: 2px; width: 80px; height: 150px; border-radius: 15px;">

    <script type="text/javascript">
    // set minutes
    var mins = 1 ;
     
    // calculate the seconds (don't change this! unless time progresses at a different speed for you...)
    var secs = mins * 10;
    
    function countdown() {
    setTimeout('Decrement()',1000);
    }
    function Decrement() {
    if (document.getElementById) {
    minutes = document.getElementById("minutes");
    seconds = document.getElementById("seconds");
    // if less than a minute remaining
    if (seconds < 59) {
    seconds.value = secs;
    } else {
    minutes.value = getminutes();
    seconds.value = getseconds();
    }
    secs--;
    setTimeout('Decrement()',1000);
    }
    }
    
    
    

    function getminutes() {
    // minutes is seconds divided by 60, rounded down
    mins = Math.floor(secs / 60);
    
    if(mins==0 && secs==0)
    {
  
     dosubmit();
    
                
   }   
    return mins;
    }
    function getseconds() {
    // take mins remaining (as seconds) away from total seconds remaining
    return secs-Math.round(mins *60);
    }
      </script>
    <script language="Javascript">
      function dosubmit() {
      alert("your exam is submitted now")

//asubmit is the name of the SUBMIT button in the form
document.forms[0].submit();

               }

    </script>  
    
    
    </head>

 <body>
    <div id="timer">
    This is only valid for the next <input id="minutes" type="text" style="width: 14px; border: none; background-color:none; font-size: 16px; font-weight: bold;"> minutes and <input id="seconds" type="text" style="width: 26px; border: none; background-color:none; font-size: 16px; font-weight: bold;"> seconds.
    </div>
 </body>   
    
   
   
   <script>
    countdown();
   </script> 
   
  
  <%= yield %>
  

</html>

app/views/questions/_form.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text, :size => "50x3" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Edit Question
<% end %>

app/views/questions/index.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<h1>Listing questions</h1>

<p>Total: <%= @questions.size %></p>
<p><%= link_to 'New Question', new_question_path %></p>

<table border="1">
  <tr>
    <th>Text</th>
    <th>Choices</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
          <li>
            <%= choice.text %>
            <% if choice.correct %> (Correct) <% end %>
          </li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>



<% content_for(:title) do %>
  All Questions
<% end %>

app/views/questions/new.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Authors::   1165536 Juliana Pena
-->

<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  New Question
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @question.text %>
</p>

<h4>Choices</h4>
<ul>
  <% @question.choices.each do |choice| %>
	 <li>
		<%= choice.text %>
		<% if choice.correct %> (Correct) <% end %>
		
		<%= form_tag({:controller => "choices", :action => "destroy"}) do %>
		  <%= hidden_field_tag :question, @question.id %>
		  <%= hidden_field_tag :choice, choice.id %>
		  <%= submit_tag "Delete" %>
		<% end %>
		
	 </li>
  <% end %>
</ul>

<h5>New Choice</h5>
<%= form_tag({:controller => "choices", :action => "create"}) do %>
  <%= hidden_field_tag :question, @question.id %>
  
  <%= label_tag :text, "Text" %><br />
  <%= text_field_tag :text %>
  <br />
  <%= check_box_tag :correct %>
  <%= label_tag :correct, "Correct" %>
  <br />
  <%= submit_tag "Create" %>
<% end %>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Question Details
<% end %>

app/views/quiz/_question.html.erb
<div>
<div class = "question">
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<%= form_tag({:controller => "quiz", :action => "answer"}) do %>
   
  <% @choices.each do |choice| %>
	 <p class="choice">
		<%= radio_button_tag(:choice, choice.id) %>
		<%= label_tag("choice_".concat(choice.id.to_s).to_sym, choice.text) %>
	 </p>
  <% end %>
  
  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
  <div class="right">
        <%= submit_tag("Submit", :class => "submit") %>
  </div>      
  
<% end %>

<% content_for(:title) do %>
  Question <%= @current + 1 %> of <%= @total %>
<% end %>
</div>
</div>
    

app/views/quiz/answer.html.erb
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<div id="feedback-choices">
  <% @choices.each do |choice| %>
	 <%# if choice.correct %>
		<%#*<p class="correct feedback-choice">%>
	 <%# elsif choice == @choice %>
		<%#*<p class="incorrect feedback-choice">%>
	 <%# else %>
		<%#*<p class="feedback-choice">%>
	 <%# end %>
		<%= choice.text %>
	 </p>
  <% end %>
</div>

<%#*<p class="feedback">%>
  <%# if @correct %>
	 <%#*Correct!%>
  <%# else %>
	 <%#*Incorrect.%>
  <%# end %>
<%#*</p>%>

<%= form_tag({:controller => "quiz", :action => "question"}) do %>
  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
<% end %>

<% content_for(:title) do %>
  Question <%= @current + 1 %> of <%= @total %>
<% end %>

app/views/quiz/end.html.erb
<h1>Quiz Results</h1>
<p id="question">You answered correctly <%= @correct %> out of <%= @total %> questions.</p>

<p id="score">YOU HAVE SCORED <%= @correct %> MARKS !</p>

<%= form_tag({:controller => "quiz", :action => "submitresult"}, :method => "get") do %>
  <div class="center">
	 <%= submit_tag("Submit the test results", :class => "submit") %>
  </div>
<% end %>


<%= form_tag({:controller => "quiz", :action => "index"}, :method => "get") do %>
  
<% end %>

<% content_for(:title) do %>
  Quiz Results
<% end %>

app/views/quiz/index.html.erb
<%= stylesheet_link_tag "style.css" %>
<h1>Start Quiz</h1>

<%= form_tag({:controller => "quiz",
				  :action => "start"}) do %>
  
  <div class="center">
	 <%= submit_tag "Start!", :class => "submit"%>
  </div>
<% end %>

<% content_for(:title) do %>
  Start Quiz
<% end %>

app/views/quiz/question.html.erb
<div class = "main">
<div class ="timer">
    <html>
    <head>
    <title>Countdown</title>
    <script type="text/javascript">
    // set minutes
    var mins = 1 ;
     
    // calculate the seconds (don't change this! unless time progresses at a different speed for you...)
    var secs = mins * 10;
    
    function countdown() {
    setTimeout('Decrement()',1000);
    }
    function Decrement() {
    if (document.getElementById) {
    minutes = document.getElementById("minutes");
    seconds = document.getElementById("seconds");
alert(seconds);

    // if less than a minute remaining
    if (seconds < 59) {
    seconds.value = secs;
    } else {
    minutes.value = getminutes();
    seconds.value = getseconds();
    }
    secs--;
    setTimeout('Decrement()',1000);
    }
    }
    
    
    

    function getminutes() {
    // minutes is seconds divided by 60, rounded down
    mins = Math.floor(secs / 60);
    
    if(mins==0 && secs==0)
    {
  
     dosubmit();
 
               
   }   
    return mins;
    }
    function getseconds() {
    // take mins remaining (as seconds) away from total seconds remaining
    return secs-Math.round(mins *60);
    }
      </script>
    <script language="Javascript">
      function dosubmit() {
      alert("go to next question")

//asubmit is the name of the SUBMIT button in the form
document.forms[0].submit();

               }

    </script>  
    </head>
    <body>
    

     

    <div id="timer">
    This is only valid for the next <input id="minutes" type="text" style="width: 14px; border: none; background-color:none; font-size: 16px; font-weight: bold;"> minutes and <input id="seconds" type="text" style="width: 26px; border: none; background-color:none; font-size: 16px; font-weight: bold;"> seconds.</div>
</div>    
    


<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<%= form_tag({:controller => "quiz", :action => "answer"}) do %>
  <% @choices.each do |choice| %>
	 <p class="choice">
		<%= radio_button_tag(:choice, choice.id) %>
		<%= label_tag("choice_".concat(choice.id.to_s).to_sym, choice.text) %>
	 </p>
  <% end %>
  
  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
<% end %>

<% content_for(:title) do %>
  Question <%= @current + 1 %> of <%= @total %>
<% end %>
<script>
    countdown();
</script>


</div>

app/views/quiz/submitresult.html.erb
<!--
# ITESM CEM, May 11, 2011.
# Ruby Source File
# Activity::  Final Project: Design Patterns Quiz App
# Author::    1165536 Juliana Pena
-->

<h1>YOUR QUIZ REPORT HAS BEEN SUCCESSFULLY SUBMITTED!!!!!</h1>
<%= form_tag({:controller => "quiz", :action => "index"}, :method => "get") do %>
  
<% end %>